source 'git@github.com:SPHTech/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

use_frameworks!

target 'TestUtilsExample' do
end

target 'TestUtilsExampleTests' do
  pod 'TestUtils', :path => '../'
end
