source 'git@github.com:SPHTech/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

use_frameworks!

target 'WebKitCleanUp-Example' do
  pod 'WebKitCleanUp', :path => '../'
end

target 'WebKitCleanUp-ExampleTests' do
  inherit! :search_paths
  pod 'WebKitCleanUp', :path => '../'
end
